name: API Gateway

on:
  push:
    paths:
      - api-gateway/**
    branches:
      - 'master'
  pull_request:
    branches: [ master ]

  workflow_dispatch: # just enabled

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./api-gateway
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-api-gateway:1.0.0
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ../gradlew build --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          ../gradlew bootBuildImage -x test -PBUILD_SOURCEVERSION=1.0.0
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME
